### ISSUE TITLE
Option to control number of FAQs output

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-faq#29] opened 2017-08-22 17:07 UTC
As requested [in the plugin forum](https://wordpress.org/support/topic/number-of-items-displayed/), users would like a way to control the number of FAQs displayed.

Suggest one or more of:
- a filter to control the default in the widget and shortcode FAQ query.
- a “Number of FAQs to Show” option for the widget.
- a “number” or “count” attribute for the shortcode.

**Comment by carasmo** [comment] 2017-08-31 16:16
I was wondering why posts_per_page wasn't added, I have many FAQs I want to add but it stopped at the posts_per_page option in reading settings. This was a bummer. For the time being, I just changed the plugin code and will make a note not to upgrade yet.

![screen shot 2017-08-31 at 12 14 28 pm](https://user-images.githubusercontent.com/1124594/29933569-1bc441b2-8e46-11e7-8017-a11f811cb5d7.png)

**Comment by cjkoepke** [comment] 2017-09-05 17:02
@carasmo @nickcernis So am I correct in assuming the only use-case for a FAQ count limit would be in the event of using a shortcode variation like `[gs_faq cat="35"]` or `[gs_faq]`?

**Comment by nickcernis** [comment] 2017-09-05 17:08
@cjkoepke That's one good use-case, yes. Users may want to specify a limit for the widget, or override the limit with a filter in their theme.

**Comment by cjkoepke** [comment] 2017-09-05 17:10
So what's the point of limiting though, unless there's pagination?

**Comment by cjkoepke** [comment] 2017-09-05 17:12
You can also achieve a limit if you comma-delimit a list of IDs — but I can see adding a simple param like `limit="10"` being an easier approach.

**Comment by nickcernis** [comment] 2017-09-05 17:23
> So what's the point of limiting though, unless there's pagination?

https://wordpress.org/support/topic/number-of-items-displayed/

Users would like to easily allow more than the default number of FAQs to be displayed without editing the global Reading Settings, which affects all post types.

**Comment by carasmo** [comment] 2017-09-05 17:39
So, when the option is added limit= I could add -1 to get all of them. The display posts shortcode has [posts_per_page](https://github.com/billerickson/display-posts-shortcode/blob/master/display-posts-shortcode.php#L79) no pagination. Tough tookies -- he won't add it (make your own loop is what he says and I agree). I use it with an FAQ cpt want to show all from a specific term or all of them and no pagination.

**Comment by cjkoepke** [comment] 2017-09-05 18:19
@nickcernis Ah, okay that forum topic explains it a bit better. So how about this for scope:

- [ ] Set limit parameter on shortcode/widget.
- [ ] Defaults to the global setting in Settings > Reading

**Comment by nickcernis** [comment] 2017-09-06 15:22
Sounds good, @cjkoepke!

**Comment by cjkoepke** [comment] 2017-09-06 18:56
@nickcernis This can be reviewed, but I've added limits to both the shortcode and widget. Defaults accurately to global setting.

**Comment by nickcernis** [comment] 2017-09-07 17:06
Looks good! I confirmed that:

- [x] Limit works in shortcode.
- [x] Multiple shortcodes on same page can have different limits.
- [x] Limit works in widget.
- [x] Multiple widgets can have different limits.
- [x] Widget defaults to posts per page count in reading settings.
- [x] Shortcode defaults to posts per page count in reading settings.
- [x] Limit in shortcode and widget can exceed posts per page in reading settings.
- [x] Widget live updates in customizer when editing FAQ Limit.

**Comment by JiveDig** [comment] 2017-11-01 20:29
Hey yall, I just posted on the WP forum but realized it's easier here. Just adding my 2-cents that I don't think this (https://github.com/copyblogger/genesis-simple-faq/issues/29#issuecomment-327260061) is the best flow. I would expected the default `[gs_faq]` shortcode to show all FAQs. If a `limit` param is used, then it uses that number. I think it would rarely ever make sense to follow posts_per_page global option. Most of the time people will want to show all, or all in a cat, or specific faqs by ID. IMHO.

**Comment by nickcernis** [comment] 2017-11-04 09:46
I agree, @JiveDig – it makes sense to have no limit as the default. Pull request sent.

**Comment by dreamwhisper** [comment] 2017-11-06 15:53
I took confirmed off of this since the pull request will need to get merged to develop, then confirmed and merged to master. This way the current pull request from develop to master doesn't assume this is resolved and get released as such.

cc @nathanrice

**Comment by dreamwhisper** [comment] 2017-11-13 17:26
Noting the PR functionality was confirmed.

**Closed** 2017-11-13 18:52 UTC
Labels: enhancement
